### ISSUE TITLE
Migrate data from frog database to lonoa database 

### ISSUE THREAD

**Issue by matthew-schultz** [erdl/lonoa#104]
Tables to migrate (unfinished)
- [x] sensor_info
   - remember to swap the query_string values of purpose_id 13 and 14 (see https://github.com/erdl/lonoa/issues/94#issuecomment-510746912)
   - no need to use purpose_id 98 and 111 https://github.com/erdl/lonoa/issues/96
- [x] reading
- [x] model_end_uses
- [x] model_scenarios
- [x] model_data
- [x] schedule_min
- [ ] Any others that are needed

**Comment by matthew-schultz** [comment]
Notes from lonoa production setup today

- Copy readings before 8/7 from frog_uhm to lonoa_frogs
- Move any tables required by @eileenpeppard for views, etc, that are not already there.
   - __HIGH PRIORITY__ Create scripts to automate exporting (and importing) of those tables 
   - Complete import process after @kathrynparadis finishes checking over views

**Comment by matthew-schultz** [comment]
Attempted to import these tables into lonoa_frogs first, since they are needed for the public views

- model_end_uses
- model_scenarios
- model_data
- schedule_min

They were migrated successfully but with the owner ```lonoa_frogs``` instead of ```sepgroup_nonmsg```

**Comment by carlosparadis** [comment]
@eileenpeppard @matthew-schultz can you do a quick check the views hosted on Github folder and whichever other ones come to mind work now in production? 

@eileenpeppard Try starting using this database stead of the old one, there should not be anything left from your end use.

**Comment by matthew-schultz** [comment]
closing since data has been migrated
