### ISSUE TITLE
Document on the sensors wiki the necessary manual permissions 

### ISSUE THREAD

**Issue by carlosparadis** [erdl/lonoa#70]
@matthew-schultz You can let me handle the wiki writing side, but let's iterate over the issue what is needed. 

From the top of my head what I know is:

 1. A user, like any other in the server, must be created called `locked_user`. Should not be sudo. 
 1. A user on the database must be created for `locked_user`. Should not be a superuser, but needs permission to create a database. This user should not have permissions to mess with databases it **not** created, but it should have read, and write table permissions to those it created. 

-- The above is done once --

We should also review the documentation on how users keep running init_crontab. We will want them to switch to locked_user when they first run init_crontab and init_database, or is it safe for them to run on another user? This will have to do with the database permissions, I think.

**Comment by matthew-schultz** [comment]
Closing this issue for now, since I've added the required permissions to the lonoa user guide in the wiki here https://github.com/erdl/lonoa/wiki/Lonoa-User-Guide
