### ISSUE TITLE
Prints and files being generated everywhere

### ISSUE THREAD

**Issue by carlosparadis** [erdl/lonoa#74]
For reasons you now know well, I am not too thrilled to have python code output files and print things everywhere. 

We should find a package that lets you enable debug mode, agree on a convention of put all files in an organized and well-structured folder, come up with a better way or remove it altogether. 

The python code should only do all these prints if executed in --verbose mode as well. We should see how other people and code do that since it is a pretty well-adopted convention.

**Comment by matthew-schultz** [comment]
Closing this issue since PR #121 was accepted
