### ISSUE TITLE
Rename status column in error_log to was_success

### ISSUE THREAD

**Issue by matthew-schultz** [erdl/lonoa#92]
Column name __was_success__ more clearly demonstrates if data_acquisition or database_insertion of script run was successful or not, compared to current column name __status__ used in error_log table.

**Comment by carlosparadis** [comment]
@matthew-schultz Can you write here the current column name so we know in the future?

**Comment by matthew-schultz** [comment]
@carlosparadis Okay, I updated the first line to include the old column name

**Comment by matthew-schultz** [comment]
closing this issue since PR #102 included this update and was accepted
